# Configuration of languages
# Documentation: https://docs.hugoblox.com/reference/multilingual/

es:
  languageCode: es
  languageName: Español
  title: DARK_NEKO
  params:
    description: 'Sitio web académico personal de Abel Elías Guzmán Del Orbe, Tecnólogo en Desarrollo de Software del ITLA.'
  menu:
    main:
      - name: Inicio
        url: /
        weight: 10
      - name: Sobre Mí
        url: /#about
        weight: 20
      - name: Publicaciones
        url: /#papers
        weight: 30
      - name: Charlas
        url: /#talks
        weight: 40
      - name: Noticias
        url: /#news
        weight: 50
      - name: Proyectos
        url: /projects/
        weight: 60
      - name: Contacto
        url: /#contact
        weight: 70
