# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://docs.hugoblox.com/reference/language/
# Default language
es:
  languageCode: es-ES
  # Uncomment for multi-lingual sites, and move English content into `es` sub-folder.
  #contentDir: content/es
# Uncomment the lines below to configure your website in a second language.
#en:
#  languageCode: en-US
#  contentDir: content/en
#  title: English website title...
#  params:
#    description: Site description in English...
#  menu:
#    main:
#      - name: Bio
#        url: '#about'
#        weight: 1
