# Navigation Links
#   To link a homepage widget, specify the URL as a hash # followed by the filename of the
#     desired widget in your content/home/ folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name:  Inicio
    url: /
    weight: 10
  - name:  Sobre Mí
    url: /#about
    weight: 20
  - name:  Publicaciones
    url: /#papers
    weight: 30
  - name:  Charlas
    url: /#talks
    weight: 40
  - name:  Noticias
    url: /#news
    weight: 50
  - name:  Experiencia
    url: /experience/
    weight: 60
  - name:  Proyectos
    url: /projects/
    weight: 70
  - name:  Enseñanza
    url: /teaching/
    weight: 80
  - name:  Contacto
    url: /#contact
    weight: 90
